name: CI checks

on:
  workflow_call:
  push:
    branches-ignore:
          - 'main'
  pull_request:
    branches:
      - "**"
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0

      - name: Ensure lockfile exists
        run: |
          if [ ! -f uv.lock ]; then
            uv lock
          fi

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run invoke all
        run: uv run invoke all
  otel:
    permissions:
      contents: read # Required. To access the private repository
      actions: read # Required. To read workflow runs
      pull-requests: read # Optional. To read PR labels
      checks: read # Optional. To read run annotations
    if: always()
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Export workflow
        uses: corentinmusard/otel-cicd-action@v4
        with:
          otlpEndpoint: ${{ secrets.OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTLP_HEADERS }}
          otelToken: ${{ secrets.OTEL_TOKEN }}
